### ISSUE TITLE
Is there a way for customize specific node, like the background color or size ?

### ISSUE THREAD

**Issue by wahyupratamaputra** [MrBlenny/react-flow-chart#101]

**Comment by ffiliz** [comment]
You can look at this examples.

**Custom node** 
https://mrblenny.github.io/react-flow-chart/index.html?path=/story/custom-components--node
https://github.com/MrBlenny/react-flow-chart/blob/master/stories/CustomNodeInner.tsx

**Custom Link**
https://github.com/MrBlenny/react-flow-chart/blob/master/stories/CustomLink.tsx
https://mrblenny.github.io/react-flow-chart/index.html?path=/story/custom-components--canvas-link

**Comment by wahyupratamaputra** [comment]
yes i saw that, 
i'm sorry that im new in react,,

how i can use these in my component ?
it said it must be .ts file and after i change to .ts it wont work

**Comment by ffiliz** [comment]
This web site  can help you.

https://www.typescriptlang.org/play/
