### ISSUE TITLE
The new feature smartRouting not working for me

### ISSUE THREAD

**Issue by orestes22** [MrBlenny/react-flow-chart#105]
Im installed the new version 0.11 but for some reason this feature is not working. However, the others options of config are working perfectly. 

Best Regards

**Comment by dmitrygalperin** [comment]
@orestes22 Can you post an example with steps to reproduce?

**Comment by orestes22** [comment]
Sorry for not investigate more deep, I noted my issue right now. 
I have customLink component in order to change the color, so i didnt copy the actual solution of LinkDefault , so i added the new code, and everything work good now.

Thansk for your faster answer and your time

**Comment by orestes22** [comment]
@dmitrygalperin Could you have and idea of how to resolve this #106 ?
