### ISSUE TITLE
Pickle demo code

### ISSUE THREAD

**Issue by vagarwal77** [MrBlenny/react-flow-chart#108]
I am seeing Pickle demo which is what exactly i need after renaming some node/port/link... 
Where i can find the code for this example ? 

Love to see this product

**Comment by robertovg** [comment]
Yes, I think a more real-life example would help a lot to see the possibilities fo this library. And the one on [this](https://github.com/MrBlenny/react-flow-chart/blob/master/images/demo.gif) looks super interesting to check.

Thanks in advance.

**Comment by MrBlenny** [comment]
Sorry, I can't share that code. Nonetheless, a similar things can be achieved by combining the `Sidebar > Drag and Drop` and `Custom Components > Node` demos in the storybook.
