### ISSUE TITLE
Jupyter Notebook as a Node component

### ISSUE THREAD

**Issue by vagarwal77** [MrBlenny/react-flow-chart#109]
Hi, 

Can i add Jupyter Notebook as a native node component with react-flow-chart? If any one have tried or had tried to add some external native component, pls share the experience along with sample code. 

Thanks
-Vivek

**Comment by MrBlenny** [comment]
I'm not quite sure what you mean but you should be able to embed anything you want by using a custom node components.
https://github.com/MrBlenny/react-flow-chart/blob/master/stories/CustomNodeInner.tsx
