### ISSUE TITLE
Custom Node Style/Standart Diamond Style

### ISSUE THREAD

**Issue by altran-fabian** [MrBlenny/react-flow-chart#113]
Hi, i am really happy that i found your project. i am currently working on something mermaid like to render flowcharts with it. As i need some kind of "Decision Node" i would like to transform the standard node to rotate(45°) and the content back to -45°. I had to hack your standard node to have transparent background instead of a white one, otherwise the standard node is always a with box behind the "diamond"

![image](https://user-images.githubusercontent.com/59995045/77538884-c066b280-6ea0-11ea-9c75-513088cc69d2.png)

the only thing now, the box shadow of the default node is showing the standard node rect.
![image](https://user-images.githubusercontent.com/59995045/77538976-e2603500-6ea0-11ea-8ac9-21a317264a17.png)

so: maybe there could be a second standard node that is transformed in diamond style, to show decisions or let the custom node handle the css for background and box-shadow over the standard node style ... 
(or maybe i don't get how to transform standard node style)

**Comment by ffiliz** [comment]
I can help if you share the code you wrote.

**Comment by altran-fabian** [comment]
Hi ffiliz, thanks for the quick response. 
Here is my flowchart component:
```
import React from "react";
import { FlowChartWithState } from "@mrblenny/react-flow-chart";
import styled from 'styled-components'

const Outer = styled.div`
  background-color:#fff;
  max-width: 300px;
  display:block;
  word-break: break-all;
`

const Inner = styled.div`
  padding: 30px;
`

const DecisionOuter = styled.div`
  background-color:#dadada;
  width: 200px;
  height: 200px;
  display:block;
  word-break: break-all;
  transform: rotate(45deg);
`

const DecisionInner = styled.div`
  padding: 20px;
  transform: translate(0px,40px) rotate(-45deg)
`


const NodeInnerCustom = ({ node, config }) => {
  console.log(node);
  switch (node.type) {
    case 'decision':
    return (
      <DecisionOuter>
        <div>
        <DecisionInner>
          <h5>{node.text}</h5>
          <p>{node.type} <i>{node.id}</i></p>
        </DecisionInner>
        </div>
      </DecisionOuter>
    )
      break;

    default:
    return (
    <Outer>
      <div style={{display:'block', width: '100%'}}>
      <img src={node.path} style={{width: 'inherit'}} />
      </div>
      <Inner>
      <h5>{node.name}</h5>
      <p>{node.type} <i>{node.id}</i></p>
      </Inner>
    </Outer>
    )
  }
}


const FlowChart = ({chartData}) => {
  return (<FlowChartWithState initialValue={chartData} Components={{
            NodeInner: NodeInnerCustom
          }} />
  )
}

export default FlowChart
```

**Comment by altran-fabian** [comment]
or is there a way like: 
```
<FlowChartWithState initialValue={chartData} Components={{
            NodeInner: NodeInnerCustom,
            NodeOuter: NodeOuterCustom
          }} />
```

**Comment by MrBlenny** [comment]
Yes, you could pass in a custom Node, not just NodeInner. See the example in the storybook:
https://github.com/MrBlenny/react-flow-chart/blob/master/stories/CustomNode.tsx
