### ISSUE TITLE
How to get data from newly created flow chart?

### ISSUE THREAD

**Issue by Nilanth** [MrBlenny/react-flow-chart#116]
Need support, I need to create a flow chart in FrontEnd and need to send the data to backend, how to get the flow chart data, so i can reproduce the flow chart by API response?

@MrBlenny  could you please help with this.

It could be better if you add this to the docs!

Thanks.

**Comment by altran-fabian** [comment]
i get to mange it like this:

add a new ref in your container: 
```
this.state = chartData
const flowchartRef = React.createRef();
```
later access it with
```
const thatData = flowchartRef.current.state
this.setState(thatData)
```
pass the ref to your chart:
```
<FlowChart ref={flowchartRef} chartData={this.state}/>
```

than in your flowchart component initialize it with React.forwardRef:
```
const FlowChart = React.forwardRef((props,ref) => {
    let chartData = props.chartData
    return (<FlowChartWithState
      ref={ref}
      initialValue={chartData}
              />)})
```

hope that helps ;)
