### ISSUE TITLE
Connections onTop of nodes

### ISSUE THREAD

**Issue by altran-fabian** [MrBlenny/react-flow-chart#119]
i would like to have the possibility to have all lines on top of the nodes.
it's easy to set all svgs to z-index: 1 to achieve the result
but sadly than it is not possible to make new links ... 

any idea how to solve this? could be a nice config options: 
```
linksOnTop: boolean
```

let me know how i can support. I love this!

**Comment by MrBlenny** [comment]
Maybe you can create a [custom link component](https://github.com/MrBlenny/react-flow-chart/blob/master/stories/CustomLink.tsx) by duplicating the [Link.default.tsx](https://github.com/MrBlenny/react-flow-chart/blob/master/src/components/Link/Link.default.tsx)  component and changing the z-index on the `<svg />` element. Ideally the `Link.default.tsx` component would accept style props but I don't have time to make this change.
