### ISSUE TITLE
Linking continues on mouse release

### ISSUE THREAD

**Issue by tantayou999** [MrBlenny/react-flow-chart#12]
When I link two nodes through clicking on the ports, it doesn't stop dragging and create the link but instead allows continuous dragging onto other ports. Not sure if this is intended.
![image](https://user-images.githubusercontent.com/10719825/55376742-509b4180-5544-11e9-8dac-818b335eb6c3.png)

**Comment by tantayou999** [comment]
Some updates after looking into the problem:
This seems like a Firefox specific issue.
I'm getting this error on the "mosueup" event which prevents linkComplete.
 > TypeError: e.path is undefined
It seems like path doesn't exist on Firefox's MouseEvent.

**Comment by MrBlenny** [comment]
Fixed in https://github.com/MrBlenny/react-flow-chart/commit/a2a1773c3e8036c6da9446df5a77bf35bf124ed8, deployed to npm as version 0.0.5

More generally, firefox performance is pretty poor. Hopefully fixed in https://github.com/MrBlenny/react-flow-chart/pull/7
