### ISSUE TITLE
Read only for a single node

### ISSUE THREAD

**Issue by guilhermeoholz** [MrBlenny/react-flow-chart#120]
I've searched on the Storybook demos but couldn't find an example for this: there's some way to disable a single node?

The reason: I'm creating a chart with a node that shouldn't be dragged or deleted, so I need it to behave like it's on read only mode.

**Comment by MrBlenny** [comment]
Not currently, you could try add some custom actions to achieve this (in a hacky way) but I agree it would be a nice feature. The [Node.wrapper.tsx](https://github.com/MrBlenny/react-flow-chart/blob/master/src/components/Node/Node.wrapper.tsx) would need to be updated wherever it reads `config.readonly`. Unfortunately I don't currently have time to add this but would gladly accept a PR.

**Comment by ielijose** [comment]
Hi @guilhermeoholz, 

I'm currently working on this feature, can you tell me a bit more about what you need? because if a node is in read-only mode, it loses the ability to link to others.

**Comment by ielijose** [comment]
Hi @guilhermeoholz:

You can test it on: https://react-flow-chart.now.sh/?path=/story/other-config--node-read-only

**Comment by guilhermeoholz** [comment]
Thank you @ielijose, that's pretty much what we've been looking for 😄
