### ISSUE TITLE
Changing Size in IChart node is not taking affect

### ISSUE THREAD

**Issue by frisky5** [MrBlenny/react-flow-chart#121]
Hi, I'm testing out the demo FlowChartWithState, and tried to set the size property in nodes inside IChart, but couldn't see any changes on the webpage after webpack rebuilding, is it something I'm doing wrong?

`export const chartSimple: IChart = {
  offset: {
    x: 0,
    y: 0,
  },
  nodes: {
    node1: {
      size: {
        width: 70,
        height: 30,
      },
      id: "node1",
      type: "output-only",
      position: {
        .........`

**Comment by MrBlenny** [comment]
The size property is for internal use to determine which nodes are visible. You should use css / custom components to define the node size.
