### ISSUE TITLE
onCanvasDrop creates two nodes

### ISSUE THREAD

**Issue by Livshind15** [MrBlenny/react-flow-chart#122]
because of React.StrictMode setState updaters will run twice in strict mode in development, This causes a double call to onCanvasDrop function and create double node

**Comment by daveabes** [comment]
Yes I was experiencing the same issue. When structuring my components differently from the examples, the on Node Dropped event is called 2 times.

**Comment by MrBlenny** [comment]
What do you suggest the solution to this is?

**Comment by prativm** [comment]
@MrBlenny  
Experiencing the same issue. it creates two nodes with different IDs.

**Comment by ChrisCardoz** [comment]
@MrBlenny Mine creates 2 nodes with the same Ids.

`[DOM] Found 2 elements with non-unique id #service: `

**Comment by ChrisCardoz** [comment]
@MrBlenny I noticed the error occurring when I started to useContext() for the state of my graph according to this example. 
https://codesandbox.io/embed/condescending-moon-jke7z

When I used this model for the state of the graph, I couldn't figure out how to update the state of the graph from the node, but I did not experience this error. 
https://github.com/MrBlenny/react-flow-chart/blob/master/stories/CustomNodeInner.tsx
