### ISSUE TITLE
Link Move errors

### ISSUE THREAD

**Issue by davidanitoiu** [MrBlenny/react-flow-chart#130]
Hi,

I moved to the 0.0.12 today and had some errors coming up with my existing code.
I haven't done any changes in-between and even tried going back to 0.0.11 and the errors are gone. So it must be related with the last merge.

The error occurs when I try to create a new link.

![image](https://user-images.githubusercontent.com/12447462/80474038-4914ba80-8947-11ea-95f4-65fa66935062.png)

![image](https://user-images.githubusercontent.com/12447462/80477161-c5110180-894b-11ea-81da-ec93824835e9.png)

**Comment by lorienberne** [comment]
Hello! I managed to fix this by adding a scale param to the chart object.
```
const chart = {
    scale: 1,
    selected_node: ..., 
    offset: {...},
    nodes: {...},
    links: {...},
    ...
}
```

**Comment by davidanitoiu** [comment]
Well I'll be... 

that was it :)
