### ISSUE TITLE
styled-components should be a peer dependency

### ISSUE THREAD

**Issue by nahumzs** [MrBlenny/react-flow-chart#133]
https://github.com/MrBlenny/react-flow-chart/blob/master/package.json#L43

Styled-components has been declared as a dependency but it should be a `peer dependency`, you can find more information about this subject on [styled-component website](https://styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library)

**Comment by MrBlenny** [comment]
Agreed, fixed here https://github.com/MrBlenny/react-flow-chart/commit/8fe1a1216cc367a82fc604b38dea968bc766090e
