### ISSUE TITLE
Nodes disappear when dragging with zoom

### ISSUE THREAD

**Issue by georginaso** [MrBlenny/react-flow-chart#138]
In the latest release (https://github.com/MrBlenny/react-flow-chart/releases/tag/0.0.12) if you set zoom in/out and moves the canvas, some nodes disappear (even if are in the visible part of the view).

The error shown in the console is: "Unable to find node on an unmounted component.".

You can reproduce the issue in the storybook:
![bug-zoom](https://user-images.githubusercontent.com/58181893/81153542-4e938580-8f83-11ea-8190-0a14d79886be.gif)

Maybe it's related to #135

**Comment by MrBlenny** [comment]
Shuld be fixed in this commit
https://github.com/MrBlenny/react-flow-chart/commit/cc7f02f02fa0a18dad5d304189e02bea36ad6535

**Comment by georginaso** [comment]
> Shuld be fixed in this commit
> [cc7f02f](https://github.com/MrBlenny/react-flow-chart/commit/cc7f02f02fa0a18dad5d304189e02bea36ad6535)

Thank you!
