### ISSUE TITLE
Zooming influences Node dragging

### ISSUE THREAD

**Issue by Wipeless** [MrBlenny/react-flow-chart#139]
Zooming (either in and out) causes the node drag to not be 1:1 with the user's input.

![Screencast 2020-05-12](https://user-images.githubusercontent.com/1523864/81730867-0ffa4100-9443-11ea-8792-56a0841a5575.gif)

**Comment by eprice122** [comment]
Adding to this issue, the behavior also occurs when using the drag and drop sidebar to add a node.

**Comment by georginaso** [comment]
I'm also interested in this ✋

**Comment by ajuhos** [comment]
I've created a PR for this: https://github.com/MrBlenny/react-flow-chart/pull/152

**Comment by ielijose** [comment]
Fixed in: #152
