### ISSUE TITLE
Implementing zoom

### ISSUE THREAD

**Issue by timminkov** [MrBlenny/react-flow-chart#14]
Hi! Thanks so much for your work on react-flow-chart so far - Using it for a personal project and it's worked perfectly.

I'm implementing zoom at the moment. Trying to figure out the best way to go about this - Since the container is just a plain div, is the best way to zoom in/out to just adjust the `zoom` property? I'm not sure I can think of another way to implement this functionality.

Thanks!

**Comment by MrBlenny** [comment]
I'd tend towards adding a css style along the lines `transfrom: scale(${chart.zoom})` to a div inside the `canvas.wrapper`. `zoom` should probably be added as a top level property alongside `offset` in the [IChart](https://github.com/MrBlenny/react-flow-chart/blob/master/src/types/chart.ts#L4) type. As such, you'd bind some onScroll handlers in the canvas wrapper and add some action handlers to adjust `chart.zoom`. PR would be appreciated :)

**Comment by Pagebakers** [comment]
@timminkov Did you manage to get this working?
