### ISSUE TITLE
How to disable backspace to remove node element

### ISSUE THREAD

**Issue by smartball** [MrBlenny/react-flow-chart#141]
I want to know how to disable backspace to remove node element (not custom node_modules).
help me please.

**Comment by davidanitoiu** [comment]
The event is checked in the CanvasInner.

try to bind this to your CanvasInner. 

```javascript
import { CanvasInnerDefault } from "@mrblenny/react-flow-chart";
import React from 'react';

const CustomCanvasInner = ({children, config, onKeyDown, ...args}) => {

    const handleKeyDown = (e) => {
        if (e.keyCode === 46) {
            return {...args.onKeyDown(e)}
        }
    }

    return (
        <CanvasInnerDefault {...args} onKeyDown={handleKeyDown}>
            {children}
        </CanvasInnerDefault>
    )
}

export default CustomCanvasInner;
```

**Comment by smartball** [comment]
> The event is checked in the CanvasInner, so you have to use a custom component to overwrite it.
> 
> ```js
> import { CanvasInnerDefault } from "@mrblenny/react-flow-chart";
> import React from 'react';
> 
> const CustomCanvasInner = ({children, config, onKeyDown, ...args}) => {
> 
>     const handleKeyDown = (e) => {
>         if (e.keyCode === 46) {
>             return {...onKeyDown(e)}
>         }
>     }
> 
>     return (
>         <CanvasInnerDefault {...args} onKeyDown={handleKeyDown}>
>             {children}
>         </CanvasInnerDefault>
>     )
> }
> 
> export default CustomCanvasInner;
> ```

Wow. It work. Thank you so much mr.@davidanitoiu .
