### ISSUE TITLE
onLinkComplete action

### ISSUE THREAD

**Issue by alexkearns** [MrBlenny/react-flow-chart#15]
I've been playing about with this package and spotted that [here](https://github.com/MrBlenny/react-flow-chart/blob/master/src/container/actions.ts#L47) it compares the `fromNodeId` and `toPortId` to determine whether or not to persist the link.

Surely this will always be true? Would this be the expected behaviour?

If not, I'm happy to put up a PR to fix it.

**Comment by MrBlenny** [comment]
Yep, good catch. The intention was to prevent links linking to themselves. Fixed [here](https://github.com/MrBlenny/react-flow-chart/commit/6a3299e283c49450272582e0e5f76f772afcda47#diff-5a121158d13f502e78c5c29411f54269R55)
