### ISSUE TITLE
Is it possible to add/edit label on links?

### ISSUE THREAD

**Issue by victoriaHan** [MrBlenny/react-flow-chart#16]
Hi, 
I have some questions.
Is it possible to add/edit label on links?
is it possible to rename the node(box)
does it work it on IE11?

This library looks good so I am considering to use it, however those above functions are needed to me. So could you please answer about it? Thank you

**Comment by alexkuz** [comment]
It doesn't have labels as far as I know, but you can easily implement it yourself, something like this:

```tsx
import { FlowChart, LinkDefault } from 'react-flow-chart';


<FlowChart
  Components={{
    Link: (props) => <><LinkDefault {...props} /><MyLinkLabel {...props} /></>
  }}
  ...
/>
```

See [LinkDefault.tsx](https://github.com/MrBlenny/react-flow-chart/blob/master/src/components/Link/Link.default.tsx) for a reference.

You can also customize Node in a same way.

**Comment by MrBlenny** [comment]
Storybook example:
[Demo](https://mrblenny.github.io/react-flow-chart/index.html?path=/story/custom-components--canvas-link)
[Code](https://github.com/MrBlenny/react-flow-chart/blob/master/stories/CustomLink.tsx)
