### ISSUE TITLE
Using plainJS for custom Node component

### ISSUE THREAD

**Issue by josephtey** [MrBlenny/react-flow-chart#176]
I need to create a custom 'Node' component for my flowchart using plain-js (no Typescript). I tried creating a new Node component using CustomNode.tsx as a reference, without importing any interfaces. However, the Node component requires certain typescript wrappers (defined by interfaces) for event listeners, and dragging functionality - hence, deleting all the interfaces (in CustomNode.tsx) to use plain JS ultimately failed to work. 

Is is possible to use plain JS to create a custom Node component without losing any core functionality (e.g. dragging, etc)? How can this be achieved?

**Comment by eprice122** [comment]
You can accomplish this with styled components (see: #113).
Check out #68 if you need to do more than this.
