### ISSUE TITLE
Add delete icon on node and link selection

### ISSUE THREAD

**Issue by mikepanayotov** [MrBlenny/react-flow-chart#18]
It would be great to have a tiny delete icon when a node and link are selected.

**Comment by MrBlenny** [comment]
Check out this [story](https://github.com/MrBlenny/react-flow-chart/blob/master/stories/SelectedSidebar.tsx) for an example deleting a link.

You can add a delete icon by passing in a custom Link component. 
Something like below (I have not tested). 

```ts
import * as React from 'react'
import { FlowChart, LinkDefault } from '@mrblenny/react-flow-chart'
import * as actions from '@mrblenny/react-flow-chart/src/container/actions'
import { cloneDeep, mapValues } from 'lodash'

const chartSimple = {} // Add some chart state

const LinkDefaultWithDelete = (onDeleteKey) => (props) => (
  <>
    <button onClick={onDelete}>Your delete button</button>
    <LinkDefault  {...props} />
  </>
) 

export class ExternalReactState extends React.Component {
  public state = cloneDeep(chartSimple)
  public render () {
    const chart = this.state
    const stateActions = mapValues(actions, (func: any) =>
      (...args: any) => this.setState(func(...args))) as typeof actions

    return (
        <FlowChart
          chart={chart}
          callbacks={stateActions}
          components={{
            Link: LinkDefaultWithDelete(stateActions.onDeleteKey) 
          }}
        />
    )
  }
}
```

Example of link deletion here: 
https://mrblenny.github.io/react-flow-chart/index.html?path=/story/sidebar--selected-sidebar

**Comment by MrBlenny** [comment]
Storybook example:
[Demo](https://mrblenny.github.io/react-flow-chart/index.html?path=/story/custom-components--canvas-link)
[Code](https://github.com/MrBlenny/react-flow-chart/blob/master/stories/CustomLink.tsx)
