### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by ParanoidAndroid19** [MrBlenny/react-flow-chart#181]
I am unable to use the following imported components,
import { Content, Page, Sidebar, SidebarItem } from '@mrblenny/react-flow-chart'
When I try to use the components, I get Error: Element type is invalid. 

The following import also does not work.
import { Content, Page, Sidebar, SidebarItem } from './components'

The following import does work.
import { FlowChartWithState } from "@mrblenny/react-flow-chart";

I am trying to render DragAndDropSidebar https://github.com/MrBlenny/react-flow-chart/blob/master/stories/DragAndDropSidebar.tsx
Any help would be appreciated!

**Comment by eprice122** [comment]
When you use npm install for this library it doesn't include the storybook demos. Notice how the imports that don't work are local to the storybook directory. You can download the project from github and add the storybook directory to your project to make this work.

**Comment by ParanoidAndroid19** [comment]
Thanks, I got it!
