### ISSUE TITLE
docs?

### ISSUE THREAD

**Issue by hyusetiawan** [MrBlenny/react-flow-chart#19]
Love the library, thank you for working on this! I have been looking all over for a declarative approach to diagram building, the other alternatives are either too imperative for my taste or just non existent. 

For the life of me, I am not able to find the docs or a getting started tutorial, I tried digging into the code itself specifically in the storybook but it's a webpacked script which makes it not really readable. Any other place I should look into?

**Comment by MrBlenny** [comment]
The src for the storybook examples is available in the [stories folder](https://github.com/MrBlenny/react-flow-chart/blob/master/stories).

There is also an example here:
https://codesandbox.io/s/4w46wv71o7
