### ISSUE TITLE
Custom Node not working properly

### ISSUE THREAD

**Issue by tristan-cunningham** [MrBlenny/react-flow-chart#192]
I am trying to make a custom node using the storybook example with minimal changes so far, but when rendered with this custom node the links disapear and you can only drag the node up and down. 

The custom node code: 

```ts
const useStyles = makeStyles({
  root: {
    border: 0,
    boxShadow: "0 3px 5px 2px rgba(255, 105, 135, .3)",
    padding: "0 5px",
    height: 50,
    width: 200,
    color: "white"
  },
  node: {
    position: "absolute",
    width: 300,
    height: 150,
    padding: 30,
    background: "#3e3e3e",
    color: "white",
    borderRadius: 10,
  }
});

export const NodeInnerCustom = ({ node, config }: INodeInnerDefaultProps) => {
  const classes = useStyles();

  const properties = node.properties as INodeInnerProps;

  if (node.type === EventNodeType.Source) {
    return (
      <div className={classes.root} style={{ background: properties.nodeData.colour }}>
        source
      </div>
    );
  } else if (node.type === EventNodeType.Predicate) {
    return (
      <div className={classes.root} style={{ background: properties.nodeData.colour }}>
        predicate
      </div>
    );
  } else {
    return (
      <div className={classes.root} style={{ background: properties.nodeData.colour }}>
        action
      </div>
    );
  }
};

export const NodeCustom = React.forwardRef(({ node, children, ...otherProps }: INodeDefaultProps, ref: React.Ref<HTMLDivElement>) => {
  const classes = useStyles();

  return (
    <div className={classes.node} ref={ref} {...otherProps}>{ children }</div>
  )
})

```

chart code:

```ts
  return (
    <div className={classes.chart}>
      <FlowChart
        key={context.key}
        chart={context.chart}
        callbacks={actionCallbacks as any}
        Components={
          {
            Node: NodeCustom, // Does not work for some reason
            NodeInner: NodeInnerCustom
          }
        }
        config={{
          showArrowHead: true
        }}
      />
    </div>
  );
```

This is with the custom node:

![custom](https://user-images.githubusercontent.com/54800333/88922933-cc0c2080-d268-11ea-9e39-f493b1550af9.png)

and without:

![without](https://user-images.githubusercontent.com/54800333/88922944-cf071100-d268-11ea-96d3-0cca07219e95.png)

**Comment by eprice122** [comment]
This is occurring because you are passing className (in ...otherProps) to NodeCustom. This overrides the properties you give with className={classes.root}

Try this out:

```  
export const NodeCustom = React.forwardRef(
  ({ node, children, className, ...otherProps }, ref) => {
    // Ignore the className prop given
    const classes = useStyles();

    return (
      <div className={classes.node} ref={ref} {...otherProps}>
        {children}
      </div>
    );
  }
);

```

Hope this helps.

**Comment by tristan-cunningham** [comment]
> 
> 
> This is occurring because you are passing className (in ...otherProps) to NodeCustom. This overrides the properties you give with className={classes.root}
> 
> Try this out:
> 
> ```
> export const NodeCustom = React.forwardRef(
>   ({ node, children, className, ...otherProps }, ref) => {
>     // Ignore the className prop given
>     const classes = useStyles();
> 
>     return (
>       <div className={classes.node} ref={ref} {...otherProps}>
>         {children}
>       </div>
>     );
>   }
> );
> ```
> 
> Hope this helps.

Ah thank you, This was the issue. Moved className after `{...otherProps}` and it worked.
