### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by danielricecodes** [MrBlenny/react-flow-chart#193]
The Pickle demo gif is *exactly* the type of complex workflow editor I need to design but I don't see any source code for that demo.  Is there any documentation, besides the demos that already exist, to help me wrap my head around how to use this library?

**Comment by zevelez** [comment]
We are having the exact same problem.
If you could please share the source code for that demo would be great.
You can contact me through j.velez2210@gmail.com

**Comment by tiagomendesmarques** [comment]
Could you please share the pickle demo code? That would be perfect. Thanks

**Comment by danielricecodes** [comment]
I've already found another library, [React Diagrams](https://github.com/projectstorm/react-diagrams), with documentation.
