### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alexswan10k** [MrBlenny/react-flow-chart#2]
Hey there. This is looking pretty interesting and would love to investigate further, but alas no license. Any chance this could be added? The package.json says MIT but there is nothing in the repo.

Keep up the good work :)

**Comment by MrBlenny** [comment]
Ooops, sorry for the delay. I've added a license file.

https://github.com/MrBlenny/react-flow-chart/commit/9016ebd391d2ffa1a05fc0201dc0cf448391de1c

**Comment by alexswan10k** [comment]
Much appreciated
