### ISSUE TITLE
Problem with 0.0.14 version (Module not found)

### ISSUE THREAD

**Issue by itsalb3rt** [MrBlenny/react-flow-chart#203]
I have a problem with the version `"@mrblenny/react-flow-chart": "0.0.14"` in Windows 10.

```
Module not found: Can't resolve 'styled-components' in 'C:\Users\user\Documents\project\node_modules\@mrblenny\react-flow-chart\src\components\Canvas'
```

Version `0.0.11` works perfect

**Comment by basyusuf** [comment]
You have to install the npm package: styled-components.
https://www.npmjs.com/package/styled-components
Command: `npm i styled-components`

**Comment by itsalb3rt** [comment]
Solved install `styled-components`

```bash
npm i styled-components
```
