### ISSUE TITLE
Backspace key triggers "onDeleteKey" action

### ISSUE THREAD

**Issue by bocksdin** [MrBlenny/react-flow-chart#211]
Is there a reason why the backspace key triggers the "onDeleteKey" action? This doesn't seem intuitive, and it prevents us from using a search input on a node.

**Comment by Nicholas27** [comment]
It very strange behaviour. Any fixes exist for this problem?

**Comment by bocksdin** [comment]
Internally the "onDeleteKey" is specifically set to trigger on the delete key and backspace key. I just wanted to know if this was important, or actually desired....

**Comment by bocksdin** [comment]
In order to prevent the backspace key from deleting the node on which the input exists (however, I still believe it should not be a trigger), setup your input as such: `<input onKeyDown={e => e.stopPropagation()} />`
