### ISSUE TITLE
Selecting Side in PortsGroup

### ISSUE THREAD

**Issue by travisfalls** [MrBlenny/react-flow-chart#215]
I'd like to line all of my ports up on the right side. I can see that there is different css based on top, bottom, left or right in PortsGroup.default but I can't figure out how I am to choose right instead of bottom. Can anyone point me to documentation or explain what to do?

**Comment by georginaso** [comment]
In the storybook you can find an example: https://mrblenny.github.io/react-flow-chart/index.html?path=/story/sidebar--drag-and-drop

You should use the "type" attribute inside each port config to set the position, e.g.:

```
const ports = {
  port1: {
    id: "port1",
    type: "right",
  },
  port2: {
    id: "port2",
    type: "bottom",
  },
};
```

**Comment by georginaso** [comment]
You can also use "input" for top side and "output" for bottom side.

['input', 'top'] -> top
['output', 'bottom'] -> bottom
['right'] -> right
['left'] -> left

**Comment by travisfalls** [comment]
Thanks @georginaso! That did it. I appreciate the help.
