### ISSUE TITLE
Some additions you might find useful

### ISSUE THREAD

**Issue by msteinmn** [MrBlenny/react-flow-chart#22]
I created a fork with a number of fixes and some additions you might find useful. I am looking for some input on whether you'd like me to create a PR. The additions are summarized like that:

- Allow nodes to be React components and not just styled divs
- Adjust for chart offset origin different than 0,0 and scrolling
- Added a resize observer to detect node size changes and re-render ports and links
- Node size now adjusts properly, re-rendering ports and links on node size change
- Allow nodes to be rotated with ports rotating accordingly. New prop orientation on the node defines the angle of rotation of the node (ports rotate automatically, the node needs to be given specific css to rotate it)
- Exported actions so that it can be used with the FlowChart component
- Added a validation function (needs some more work) for new links
- Added nodeProps prop to Flowchart so that data can be sent to e.g. autocomplete menu options inside nodes (spread to Node and InnerNode)
- Added boolean snap prop to Flowchart to enable snap to grid for node placements

https://github.com/SteamFab/react-flow-chart/commits/PortPositionChange
branch PortPositionChange, specific changes are separated by commit

**Comment by MrBlenny** [comment]
Thanks @msteinmn, sorry for the slow reply. Create a PR and I'll look at merging the changes. Great work!

**Comment by nathan-haines** [comment]
@MrBlenny have you had a spare moment to check out these changes?
