### ISSUE TITLE
When dragging node, link component moves fast than the node one

### ISSUE THREAD

**Issue by jovenlumaas** [MrBlenny/react-flow-chart#221]
Hi!

I have a problem implementing workflow using this package:

![Untitled](https://user-images.githubusercontent.com/48155857/101300394-6a8c3c00-3870-11eb-889b-df761080fa25.png)

**Comment by phakhee** [comment]
Yes i'm experiencing the same, downgrading to 0.0.13 fixed the problem, but I just started using it so I do want to use the latest version.

**Comment by jovenlumaas** [comment]
hello @phakhee!

I tried downgrading my version to 0.0.13 but I got the same result.

**Comment by jovenlumaas** [comment]
@phakhee I tried downgrading to version 0.0.13 and it worked! Thank you
