### ISSUE TITLE
Warnings about without using React.forwardRef()

### ISSUE THREAD

**Issue by jitaozhang-bsn** [MrBlenny/react-flow-chart#24]
![image](https://user-images.githubusercontent.com/52178045/60375494-5d51f900-99be-11e9-9ce2-617a0f9c0d9b.png)

**Comment by jitaozhang-bsn** [comment]
If you have time, please fix it. Thanks!

**Comment by jitaozhang-bsn** [comment]
I use redux to manage the state and the state change, but the topology stay the same. I am not sure the reason is this bug or not?

**Comment by MrBlenny** [comment]
I have not been able to replicate this. What version of react are you using?

**Comment by jitaozhang-bsn** [comment]
react 16.8.6

**Comment by mikepanayotov** [comment]
I experience the same

**Comment by David-Melo** [comment]
Getting this same warning when attempting to use a custom node like in one of the examples.

React Version: 16.8.6

**Comment by virgincodes** [comment]
y is this issue closed been working on this bug for 2 days now
