### ISSUE TITLE
wrong line position, when i move sidebar to left side

### ISSUE THREAD

**Issue by MorganaUzhgorod** [MrBlenny/react-flow-chart#25]
Hi 🖖
Have some troubles with line position, when i move sidebar to left side :( 

So, mouse is still clicked! When I unpress mouse button, it will fall into right place

Here is screenshot 👇
![1](https://user-images.githubusercontent.com/8722709/60603288-2a44a680-9dbe-11e9-96a5-eb0555a668ee.png)

**Comment by DaniloSansi** [comment]
same here, did someone find a solution for that?
