### ISSUE TITLE
Wrong line behavior in FF

### ISSUE THREAD

**Issue by rkarakulov** [MrBlenny/react-flow-chart#26]
![image](https://user-images.githubusercontent.com/3773028/60728969-4a08d580-9f4a-11e9-9fd2-f0d699839b5c.png)

The line is divided in FF when you try to connect two points

**Comment by MrBlenny** [comment]
Is this still happening? I cannot replicate it in FF 63.0 or 68.0.2

**Comment by rkarakulov** [comment]
Yes, now it works, thanks
