### ISSUE TITLE
Callbacks events not working in JSX

### ISSUE THREAD

**Issue by Naveenraj006** [MrBlenny/react-flow-chart#38]
My callback actions are not working in JSX.
```
const StateActions={
			onDragNode:onDragNode,
			onDragCanvas:function(event, data){alert("dragged")}
		}


```

**Comment by phlickey** [comment]
Hey @Naveenraj006 ,

The functions that get passed to the `callbacks` prop of the `Flowchart` component need to return the function that gets called.

Try with the following:
```js
const StateActions={
			onDragNode:onDragNode,
			onDragCanvas: function(event, data){return function(){alert("dragged")}}
		}```

**Comment by DNosralla** [comment]
Actually this works fine:

```
const stateActions = {
  onDragCanvas: function(event, data){ alert("dragged", event, data)}
}
```

Maybe forgot to pass it in the props?
`<FlowChart chart={chart} callbacks={stateActions}  />`
