### ISSUE TITLE
Some feature suggestions

### ISSUE THREAD

**Issue by alexkuz** [MrBlenny/react-flow-chart#4]
Hi, I'm going to update our internal tools that use a similar component and yours looks like a promising replacement. However, I'll need some improvements to match current functionality, like:

- customizable node connections;
- automatic port positioning:
![](https://media.giphy.com/media/1dNNcsfRtZTCZ2QjCJ/giphy.gif)
- rendering only nodes in view - for performance, `react-window`-style

Are you up for PRs? Pleas let me know if any of this is out of scope for your lib. Thanks!

**Comment by MrBlenny** [comment]
PRs certainly welcome!

Regarding automatic port positioning... Have a look at the [Ports Component](https://github.com/MrBlenny/react-flow-chart/blob/master/src/components/Ports/Ports.default.tsx). I imagine you'll want to [pass in](https://github.com/MrBlenny/react-flow-chart/blob/master/src/components/FlowChart/FlowChart.tsx#L115) `chart` and use `charts.link` to determine which side the port should be on.
