### ISSUE TITLE
Question: How to have multiple nodes inside a container node

### ISSUE THREAD

**Issue by SamuelTassell** [MrBlenny/react-flow-chart#41]
Just wondering the best way to do this... imagine 3 joined nodes that act as containers, in each of the container nodes are other nodes connected. Would the best practice be to call another instance of the flow chart within a custom node type of say `container`?

**Comment by SamuelTassell** [comment]
hmm great. I'll give it a shot. Thanks :)

**Comment by orestes22** [comment]
@SamuelTassell @MrBlenny  Could you provide an example of how to do it? I have a list of IChart , and i want the user can Drag and Drop one element of this list. But I having problems because the example only work with INode.

Thanks for your time and Best Regards

**Comment by tahmid-shahriar-lincx** [comment]
an example in storybook of this would be nice
