### ISSUE TITLE
BUG: "TypeError: Converting circular structure to JSON" when trying to stringify state

### ISSUE THREAD

**Issue by voinbobar** [MrBlenny/react-flow-chart#47]
When using your code from [this issue](https://github.com/MrBlenny/react-flow-chart/issues/30), and adding a single button which logs the chart in the console, I get the following error after I move node with id "node2". It only happens with snapToGrid set to false.

I believe the issue lies in the **position** property on the node, which holds several new values like "deltaX, deltaY, lastX, lastY, **node**", with the latter being a reference to the DOM node.

```javascript
import React, { useState, useEffect } from 'react';
import { FlowChart } from '@mrblenny/react-flow-chart';
import * as actions from '@mrblenny/react-flow-chart/src/container/actions';
export default function ChatEditor() {
  let [chart, updateChart] = useState({
    offset: {
      x: 0,
      y: 0
    },
    nodes: {
      node1: {
        id: 'node1',
        type: 'output-only',
        position: {
          x: 0,
          y: 0
        },
        ports: {
          port1: {
            id: 'port1',
            type: 'output',
            properties: {
              value: 'yes'
            }
          },
          port2: {
            id: 'port2',
            type: 'output',
            properties: {
              value: 'no'
            }
          }
        }
      },
      node2: {
        id: 'node2',
        position: {
          x: 300,
          y: 100
        },
        type: 'input-output',
        ports: {
          port3: {
            id: 'port3',
            type: 'output'
          },
          port4: {
            id: 'port4',
            type: 'input'
          }
        }
      }
    },
    links: {},
    selected: {},
    hovered: {}
  });

  let stateActionCallbacks = Object.keys(actions).reduce((obj, key, idx) => {
    obj[key] = (...args) => {
      let action = actions[key];
      let newChartTransformer = action(...args);
      let newChart = newChartTransformer(chart);
      updateChart({ ...chart, ...newChart });
      return newChart;
    };
    return obj;
  }, {});
  return (
    <div>
      <div
        onClick={() => {
          try {
            console.log(JSON.stringify(chart.nodes['node2'].position));
          } catch (e) {
            console.log(e, chart.nodes['node2']);
          }
        }}
      >
        get state
      </div>
      <FlowChart chart={chart} callbacks={stateActionCallbacks} />
    </div>
  );
}
```
screenshot:

![screenshot](https://i.imgur.com/pQoTPVa.png)

[codesandbox demo](https://codesandbox.io/s/festive-sunset-u5iqe)

**Comment by sibeshkar** [comment]
HI, I got the same issue. If you just want to log or send the chart, then one can delete the 'position' or repurpose it using a function like this and it works without error. : 

`
import { cloneDeep } from "lodash";
const ProcessState = state => {
  let newChart = cloneDeep(state);
  for (var key in newChart.nodes) {
    if (newChart.nodes.hasOwnProperty(key)) {
      delete newChart.nodes[key].position;
    }
  }
  return newChart;
};
`

**Comment by emmagoldblum** [comment]
Same issue here, i fixed the problem by deleting the key node in the position and in the offset in the functions "onDragCanvas" and "onDragNode"

**Comment by outianleiz** [comment]
Same issue, I reset node in offset to 0 before  JSON.stringify().
