### ISSUE TITLE
Custom Node (not inner node) doesn't work

### ISSUE THREAD

**Issue by emmagoldblum** [MrBlenny/react-flow-chart#48]
I'm working on an environment with React : 16.8.3 
I tried to follow this example : https://github.com/MrBlenny/react-flow-chart/blob/master/stories/CustomNode.tsx

It simply didnt work : the style I tried to apply is absolutely not rendered and when i open the console to try to see the structure of the html and find the classnames generated, i find absolutely nothing.

**Comment by krashdifferent** [comment]
I had a similar issue but resolved it by forwarding props to the outer div for my custom component. In the stroybook this is done with {...otherProps}

**Comment by mgcostaParedes** [comment]
Try to use the version 0.0.6 and see if it works, i suspect there´s a bug in the custom node after that version, otherwise it´s the example is out of date

**Comment by krashdifferent** [comment]
If you are not using Styled Components (I actually use material ui's solution to take advantage of its themes) you need to merge the className and styles passed through the props. "clsx" is a small library for merging class names and styles can be done using a spread operator. style={{...style, background:"red", etc.}}. At least this has worked for me. Positioning is done though transforms so be careful overriding them. I have not had issues with links once everything is properly getting propagated.

**Comment by emmagoldblum** [comment]
@krashdifferent thanks for your response ! Can you please show me a quick example of a customNode class with clsx and all the props properly propagated please ? I tried already to passe the styles using the spread operator but i didn't manage to make it works...

**Comment by krashdifferent** [comment]
I have omitted the css but the following works for me. Are you also forwarding the ref?

`function Node(props, ref){
    const {config, isSelected, node, className, ...rest} = props;

    return (
        <div ref={ref} className={clsx(className, "fcNode", isSelected && "-selected", node.type && ("type-" + node.type))} {...rest}/>
    );
}
export default React.forwardRef(Node);`

**Comment by krashdifferent** [comment]
I have omitted the css but the following works for me. Have you forwarded the ref as well?
`
function Node(props, ref){
    const {config, isSelected, node, className, ...rest} = props;

    return (
        <div ref={ref} className={clsx(className, "fcNode", isSelected && "-selected", node.type && ("type-" + node.type))} {...rest}/>
    );
}
export default React.forwardRef(Node);
`

**Comment by krashdifferent** [comment]
I have omitted the css but the following works for me. Have you forwarded the ref as well?

function Node(props, ref){
const {config, isSelected, node, className, style, ...rest} = props;

return (
    <div ref={ref} style={{...style, background: "#FF00FF80"}} className={clsx(className, "fcNode", isSelected && "-selected", node.type && ("type-" + node.type))} {...rest}/>
);

}
export default React.forwardRef(Node);

**Comment by emmagoldblum** [comment]
It worked, thanks a lot ! 
Little note : config is not used so i deleted it (it's in ...rest now)

**Comment by krashdifferent** [comment]
Good to hear it's working. I pull out config as React, at least in dev, will post warnings to the console when the base Components are passed unrecognized props.
