### ISSUE TITLE
Custom Node Links bug after upgrade to 0.0.7

### ISSUE THREAD

**Issue by mgcostaParedes** [MrBlenny/react-flow-chart#50]
Hello after upgrading the package to the new version, i am getting the linked lines visually incorrect like the following image:

![flowchart-bug](https://user-images.githubusercontent.com/16031444/66503427-244a1a00-eabf-11e9-8800-d38fbafcd9e0.PNG)

I am using the following component to draw the custom node:
```
import * as React from 'react'
import styled from 'styled-components'

const Start = styled.div`
  position: absolute;
  width: 200px;
  height: 55px;
  padding: 20px;
  display: flex;
  justify-content: center;
  align-items: center;
  background-image: linear-gradient(45deg,#23bcbb,#45e994);
  color: #fff;
  border-radius:5px;
  -webkit-box-shadow: 0px 1px 5px -1px rgba(0,0,0,0.62);
-moz-box-shadow: 0px 1px 5px -1px rgba(0,0,0,0.62);
box-shadow: 0px 1px 5px -1px rgba(0,0,0,0.62);
`

const End = styled.div`
  position: absolute;
  width: 200px;
  height: 60px;
  padding: 20px;
  display: flex;
  justify-content: center;
  align-items: center;
  background-image: linear-gradient(45deg,#ee0979,#ff6a00);
  color: #fff;
  border-radius:5px;
  -webkit-box-shadow: 0px 1px 5px -1px rgba(0,0,0,0.62);
-moz-box-shadow: 0px 1px 5px -1px rgba(0,0,0,0.62);
box-shadow: 0px 1px 5px -1px rgba(0,0,0,0.62);
`

const InputDiv = styled.div`
  position: absolute;
  width: 200px;
  height: 135px;
  padding: 20px;
  display: flex;
  justify-content: center;
  align-items: center;
  background: #fff;
  border-radius:5px;
  -webkit-box-shadow: 0px 1px 5px -1px rgba(0,0,0,0.62);
-moz-box-shadow: 0px 1px 5px -1px rgba(0,0,0,0.62);
box-shadow: 0px 1px 5px -1px rgba(0,0,0,0.62);
`


const Node = ({ node, children, ...otherProps }) => {
  if(node.type === 'output-only') {
    return (
      <Start {...otherProps}>
        {children}
      </Start>
    )
  } else if(node.type === 'input-only') {
    return (
      <End {...otherProps}>
        {children}
      </End>
    )
  } else {
    return (
      <InputDiv {...otherProps}>
        {children}
      </InputDiv>
    )
  }
}

const NodeFlowchart = React.forwardRef((props, ref) => (
  <Node {...props} innerRef={ref} />
));


export { NodeFlowchart }
```
Any ideas why it´s not working properly?

Thank you, 
cheers.

**Comment by emmagoldblum** [comment]
Hi, 

My guess is that the function that calculate the position of ports is not called with custom styled.div, the name of the function is onPortPositionChange, and it doesn't appear in the props passed to the custom node component (in the otherProps). I made a little test where i am passing NodeDefault as a customNode, and I had the same bug, and it appears that NodeDefault doesnt have this function as props either. The NodeWrapper has it. 

Do you think it could be that ?

**Comment by mgcostaParedes** [comment]
Hello, yes, that should be the problem, someone already implemented some other way to fix that issue? 

Thank you.

**Comment by emmagoldblum** [comment]
Hi again, 
thanks to the help of another user, i think it might be a problem of ref. 

This code is actually working for me : 

export const CustomNode = forwardRef((props, ref) => <Node innerRef={ref} {...props} />)

const Node = ({ innerRef, isSelected, node, className, style, ...rest }) => (
  <div
    className={clsx(className, 'fcNode', isSelected && '-selected', node.type && `type-${node.type}`, 'custom-node')}
    ref={innerRef}
    style={{ ...style }}
    {...rest}
  />
)

Do you think passing the props innerRef as ref into the styledComponent might fix it ?

**Comment by krashdifferent** [comment]
NodeWrapper passes the callback to the PortWrapper which calculates position on component update life cycle. I don't have this issue but am not sure exactly what you are doing differently to cause it. I hav eonly used and looked at 0.7 so I don't know what was changed on that update. I use my own container to manage the state more directly but should still be using the default actions to manage position updates. I'm assuming you are using FlowChartWithState? If you are using the stateless FlowChart, you would need to manually add the port positions to the chart object. Are you using custom components for Port or Ports?

**Comment by timbrunette** [comment]
I had the same issue, have taken the storybook example for the NodeCustom and modified it to the following:

`const NodeCustom = forwardRef(({ node, children, ...otherProps }, ref) => {
  if (node.type === 'output-only') {
    return (
      <DarkBox ref={ref} {...otherProps}>
        {children}
      </DarkBox>
    );
  } else {
    return (
      <Circle ref={ref} {...otherProps}>
        {children}
      </Circle>
    );
  }
});
`

And then include it in the Components as a custom component similar to the storybook example here: stories/CustomNode.tsx
