### ISSUE TITLE
Links that goes from one port on a node to another port of the same node are not visible (and clickable)

### ISSUE THREAD

**Issue by emmagoldblum** [MrBlenny/react-flow-chart#52]
Because of how the links are made (calculated ?), when you want to strech a link between to port of a same node, if the ports are on different sides of the node, it's almost impossible to see them and click on them.

![demo_link_react_flow_chart](https://user-images.githubusercontent.com/29426555/66755266-ede21580-ee97-11e9-9074-0920601afd77.gif)

**Comment by MrBlenny** [comment]
Fixed if you enable smartRouting
https://mrblenny.github.io/react-flow-chart/index.html?path=/story/other-config--smart-link-routing
https://github.com/MrBlenny/react-flow-chart/blob/master/stories/SmartRouting.tsx
