### ISSUE TITLE
Add support for "smart" link routing

### ISSUE THREAD

**Issue by dmitrygalperin** [MrBlenny/react-flow-chart#54]
Are there any plans to implement a "smart" link routing prop, where instead of taking the shortest path between two ports, links will avoid collision with other nodes to give the chart a neater appearance? Example attached
![nodes](https://user-images.githubusercontent.com/25541221/66958103-7d70fb00-f035-11e9-98a9-2c1d9ffbea45.png)

**Comment by MrBlenny** [comment]
I'm unlikely to have time to work on such a feature. Certainly not for at least a few months. Happy to accept PRs :)

**Comment by dmitrygalperin** [comment]
@MrBlenny Thanks, I'll see if I can put together a PR.

**Comment by dmitrygalperin** [comment]
I have a fork at https://github.com/dmitrygalperin/react-flow-chart/tree/master that implements this via  `config={{ smartRouting: true }}`

 If anyone would like to take a look or offer suggestions/concerns before I submit a PR, please feel free.

Some concerns:

Pathfinding is expensive so performance is slower. I am limiting pathfinding to only nodes that are in view as well as scaling down the resolution of the pathfinding matrix. As a fallback to when a path cannot be found, I create a direct right angle link between the ports. 

I also feel that the pathfinding can be tweaked to make the paths neater, though I'm not sure exactly how, especially with performance in mind.

**Comment by MrBlenny** [comment]
@dmitrygalperin is that ready to be a PR?

**Comment by Pagebakers** [comment]
@dmitrygalperin @MrBlenny  Any news? Would really like this to be merged!

**Comment by Pagebakers** [comment]
I just merged this in to my project, but I don't see any difference with smartRouting enabled. @dmitrygalperin is this the latest version you shared?

**Comment by mchaledg19** [comment]
**config={{ smartRouting: true }}** doesn't work on my project. Any news for smart link?
` <FlowChart
          chart={chart}
          callbacks={stateActions}
          config={{
            smartRouting: true,
            // disabledPorts: [],
            validateLink: ({
              linkId,
              fromNodeId,
              fromPortId,
              toNodeId,
              toPortId,
              chart
            }) => {
              if (chart.nodes[fromNodeId].type === chart.nodes[toNodeId].type)
                return false;
              return true;
            }
          }}
          Components={{
            CanvasOuter: CanvasOuterCustom,
            NodeInner: NodeInnerCustom,
            Port: PortCustom,
            Link: props => <LinkCustom {...props} stateActions={stateActions} />
          }}
        />`

**Comment by Pagebakers** [comment]
The problem has probably to do with your custom port/link components. Remove those and it should work :)

**Comment by dmitrygalperin** [comment]
@MrBlenny @Pagebakers 

Apologies, I'm just now getting time to get back to this. I think it's ready for a PR

**Comment by mchaledg19** [comment]
any update? if this is already merged?

**Comment by hyusetiawan** [comment]
@MrBlenny ping, would love to get the smart routing merged :)

**Comment by MrBlenny** [comment]
Yep, planning on getting to this over the coming weekend.
