### ISSUE TITLE
Right angle links between nodes

### ISSUE THREAD

**Issue by fenech** [MrBlenny/react-flow-chart#55]
I wrote a function to generate straight line links between nodes, but hit a limitation:

![right angle links between nodes](https://user-images.githubusercontent.com/3943705/67583802-9754c100-f74c-11e9-9a3c-73f641917700.png)

I used the same logic as in `generateCurvePath` to determine whether the link was "horizontal" (i.e. width > height) to switch between the two link shapes, but I think that it makes more sense to base the behaviour on which edge of the node the link enters/exits. That is, a link from the top/bottom of a node should start vertical, whereas a link from the left/right should start horizontal.

Would it make sense to add the `chart` state to the list of props passed to the `<Link>` component, to make it possible to look up the port and make this decision within the component?

I guess that in order to implement #54, it would also be necessary to look at the whole chart state in order to decide where to put each line.

**Comment by dmitrygalperin** [comment]
I started working on my PR for #54. You actually have access to the port data in Link.wrapper. You can pass down the port type to Link and then use it in generateCurvePath to figure out which direction to start in

**Comment by MrOrz** [comment]
We also need to access more data in inner component (`<Port>` in our case). In the end we decided to add extra properties to `config` prop.

Actually there was once a prop called `nodeProps` in config: https://github.com/MrBlenny/react-flow-chart/blob/master/src/types/config.ts#L9 . At that time the `nodeProps` is used to pass down all components: https://github.com/MrBlenny/react-flow-chart/commit/2dfa8ab5e2c2ae67f8fc1d338431a43f1e9f84f7 . However, the latest API passes the whole config down to each component, thus codes relevant to `nodeProps` is removed in the code base. I guess this means that it is encouraged to put extra stuff in config...?

**Comment by fenech** [comment]
@MrOrz in this case, I guess it would make sense to use `config` to specify the link type (e.g. "curved" or "angular") but I would still need to pass the sides of the ports at `link.to` and `link.from`. Are you suggesting that I add extra properties to `config` from inside `Link.wrapper` (and @MrBlenny can I interpret that your :+1: is approving that idea)?

Something like:
```typescript
config = {
   ...config,
   portConfig: {
    to: "bottom",
    from: "top"
  }
}
```
