### ISSUE TITLE
How to get sidebar (drag and drop)

### ISSUE THREAD

**Issue by vinhyenvodoi98** [MrBlenny/react-flow-chart#60]
After i install `@mrblenny/react-flow-chart` how i can code sidebar (drag and drop) like this
https://mrblenny.github.io/react-flow-chart/index.html?path=/story/sidebar--drag-and-drop

and return data (after use drag and drop ) about flowchart like :
```js
            chartSimple: {
                offset: {
                    x: 0,
                    y: 0
                },
                nodes: {
                    node1: {
                        id: 'node1',
                        type: 'output-only',
                        position: {
                            x: 300,
                            y: 100
                        },
...
```
thanks .

**Comment by MehdiSaffar** [comment]
Try using FlowChart instead of FlowChartWithState and console log the state after the drop happens.

**Comment by MrBlenny** [comment]
https://github.com/MrBlenny/react-flow-chart/blob/master/stories/DragAndDropSidebar.tsx
