### ISSUE TITLE
[Question] Is there any way to read-only certain nodes or certain links?

### ISSUE THREAD

**Issue by Dina-Lai** [MrBlenny/react-flow-chart#66]
I know we can overwrite the flow chat config to set the whole flow chat read-only like the:
```
export const ReadonlyMode = () => {
  return (
    <Page>
      <FlowChartWithState config={{ readonly: true }} initialValue={chartSimple}/>
    </Page>
  )
}
```

but I want to set certain nodes or certain links read-only and cannot drag

Is there any methods?

**Comment by emmagoldblum** [comment]
What i did is that I implemented the component FlowChart, and not FlowChartWithState, and i've overwritten the functions onDragNode to make it impossible to drag nodes of some types that i specified :)

**Comment by Dina-Lai** [comment]
I'll try it, thx!
