### ISSUE TITLE
How can we display port on custom position?

### ISSUE THREAD

**Issue by ImranBinShoukat** [MrBlenny/react-flow-chart#69]
I want to do something like this:

```
ports: {
  port1: {
    id: 'port1',
    type: 'left',
    position: {
      x: 50,
      y: 75
    }
  }
}
```

But it ignores the position and displays port on left side of the node. Is there a way to display port on specified position?

**Comment by krashdifferent** [comment]
I believe the only way to give custom port positions it to override the Ports component with a custom component passed to the Components prop of the flow chart. You can check out the default Ports and PortsGroup components for how to make these.
