### ISSUE TITLE
event callbacks dont work with .jsx...

### ISSUE THREAD

**Issue by mrkchang** [MrBlenny/react-flow-chart#70]
Here's the code...
export default class FlowChart extends Component {
    render() {
        // const stateActions = mapValues(actions, (func: any) =>
        // (...args: any) => this.setState(func(...args))) // as typeof actions

        const callbacks = {
            onDragCanvas: (event, data) => { console.log("onDragCanvas", event, data)},
            onDrop: (event, data) => { console.log("onDrop", event, data)},
            onCanvasDrop: (event, data) => { console.log("onCanvasDrop", event, data)},
        }
    
        return (
            <FlowChartWithState 
                initialValue={chartSimple}
                callbacks={callbacks}
                // Components={ { Port: PortCustom, }}

            />
        )
    }
}

**Comment by elbrodelche** [comment]
Im having the same prolblem It seems that <FlowChartWithState> doest accept callbacks. The callbacks are taken from an actions file, but i dont see how to manage that. Can anybody give some advice?. I just want to put a click listener on every node.

**Comment by v4irajvimu** [comment]
Hi @MrBlenny can you have a look on this pls

**Comment by v4irajvimu** [comment]
@elbrodelche @mrkchang  can you have a look on this closed issue, please? it may solve the problem.
https://github.com/MrBlenny/react-flow-chart/issues/30
