### ISSUE TITLE
Drag node without selecting it (distinguish between drag and click)

### ISSUE THREAD

**Issue by fenech** [MrBlenny/react-flow-chart#77]
I was wondering if there was any way to move a node around the canvas without selecting it at the same time?

I found this issue in react-draggable (the underlying library used by react-flow-chart) https://github.com/mzabriskie/react-draggable/issues/49 which suggests setting some state `isDragging` when dragging starts, and ignoring all clicks until dragging stops. 

In order to do this, it would be necessary to update the `Node.wrapper` component. Would a PR be welcome?

Alternatively, are there any other solutions that are currently supported?

**Comment by MrBlenny** [comment]
Yep, I think a PR would be required. [onNodeClick](https://github.com/MrBlenny/react-flow-chart/blob/master/src/components/Node/Node.wrapper.tsx#L127) should only be called if dragging is not active.
