### ISSUE TITLE
GIF Example

### ISSUE THREAD

**Issue by guiassemany** [MrBlenny/react-flow-chart#80]
Hello Guys,

I am working on a new tool and the initial GIF is a perfect example of what I want to achieve. Is that code available as an example of this library usage?

Thank you!

**Comment by MrBlenny** [comment]
Nope, sorry. It is a private project. The best partial examples are:
https://mrblenny.github.io/react-flow-chart/index.html?path=/story/sidebar--drag-and-drop
https://mrblenny.github.io/react-flow-chart/index.html?path=/story/custom-components--node-inner

**Comment by guiassemany** [comment]
Thank you!
