### ISSUE TITLE
Render components flow chart

### ISSUE THREAD

**Issue by nguyenvanhientth** [MrBlenny/react-flow-chart#83]
data update but UI not update..
<img width="1377" alt="Screen Shot 2020-02-12 at 14 48 59" src="https://user-images.githubusercontent.com/32895878/74313719-d021b000-4da6-11ea-8fc1-ad50200378f2.png">

**Comment by MrBlenny** [comment]
Please provide more information

**Comment by donezombie** [comment]
Hi @MrBlenny ,
Please check this reproduction of this issue: https://codesandbox.io/s/nice-dawn-cil5j
I've tried to change data and component re-rendered but UI haven't updated :(

**Comment by ffiliz** [comment]
This can help you

https://llt5y.csb.app/

**Comment by donezombie** [comment]
@ffiliz
Cheers. Thank you so much!
