### ISSUE TITLE
Exporting diagams into json

### ISSUE THREAD

**Issue by BboyAkers** [MrBlenny/react-flow-chart#9]
Curious to know if you've developed the functionality for diagrams to be exportable into json?
Example: If I create a diagram. I'd like to export it into json via a file or an open post call for a server to consume.

**Comment by MrBlenny** [comment]
You'd need to write a few lines. Have a look at the [ExternalReactState](https://github.com/MrBlenny/react-flow-chart/blob/master/stories/ExternalReactState.tsx) example. You can read `this.state` and write it to a file or make an http request.
