### ISSUE TITLE
Info: Where I can find code example?

### ISSUE THREAD

**Issue by orestes22** [MrBlenny/react-flow-chart#91]
Hi, Where i can find the code example of this image? 
https://github.com/MrBlenny/react-flow-chart/blob/master/images/demo.gif

Because this demo represent each thing i have to do with the library and it will help a lot and save time if i can check the code and understand how you did it. 

Best Regards and Thanks for your time

**Comment by ffiliz** [comment]
You can do this by looking at storybook examples.

https://mrblenny.github.io/react-flow-chart/index.html?path=/story/state--internal-react-state

Codes of examples in storybook

https://github.com/MrBlenny/react-flow-chart/tree/master/stories
